fronted_buscar_login:
    path:    /
    defaults: { _controller: FrontedBundle:Default:loginFull }

fronted_login:
    path:    /buscar
    defaults: { _controller: FrontedBundle:Default:loginFull }

fronted_buscar_cliente:
    path:    /buscar/cliente
    defaults: { _controller: FrontedBundle:Default:buscarCliente }

fronted_pagar_cliente:
    path:    /pagar/cliente/{id}
    defaults: { _controller: FrontedBundle:Default:pagarCliente }

fronted_cambiar_fecha_pago:
    path:    /cambiarFechaPago/cliente/{id}
    defaults: { _controller: FrontedBundle:Default:cambiarFechaPagoCliente }

fronted_cambiar_fecha_pagoSave:
    path:    /cambiarFechaPagoSave/cliente/{id}
    defaults: { _controller: FrontedBundle:Default:cambiarFechaPagoClienteSave }

fronted_registrar:
    path:    /registrar
    defaults: { _controller: FrontedBundle:Default:registrar }

fronted_edit_cliente:
    path:    /edit/cliente/{id}
    defaults: { _controller: FrontedBundle:Public:editCliente }

fronted_cliente_update:
    path:    /update/cliente/{id}
    defaults: { _controller: FrontedBundle:Public:updateCliente }

fronted_registrarSave:
    path:    /registrarSave
    defaults: { _controller: FrontedBundle:Default:registrarSave }

fronted_public:
    path:    /index
    defaults: { _controller: FrontedBundle:Public:indexPublic }

fronted_public_pago_adelantado:
    path:    /pagoAdelantado/cliente/{id}
    defaults: { _controller: FrontedBundle:Public:pagoAdelantadoCliente }

fronted_public_pago_adelantado_save:
    path:    /pagoAdelantadoSave/cliente/{id}
    defaults: { _controller: FrontedBundle:Public:pagoAdelantadoClienteSave }

fronted_public_cliente_mes:
    path:    /cliente/mes/
    defaults: { _controller: FrontedBundle:Public:clienteMes }