pagosClientes:
    path:     /
    defaults: { _controller: "FrontedBundle:Pago:index" }

pagosClientes_show:
    path:     /{id}/show
    defaults: { _controller: "FrontedBundle:Pago:show" }

pagosClientes_new:
    path:     /new
    defaults: { _controller: "FrontedBundle:Pago:new" }

pagosClientes_create:
    path:     /create
    defaults: { _controller: "FrontedBundle:Pago:create" }
    requirements: { _method: post }

pagosClientes_edit:
    path:     /{id}/edit
    defaults: { _controller: "FrontedBundle:Pago:edit" }

pagosClientes_update:
    path:     /{id}/update
    defaults: { _controller: "FrontedBundle:Pago:update" }
    requirements: { _method: post|put }

pagosClientes_delete:
    path:     /{id}/delete
    defaults: { _controller: "FrontedBundle:Pago:delete" }
    requirements: { _method: post|delete }

pagosClientes_confirm_delete:
    path:     /{id}/confirm/delete
    defaults: { _controller: "FrontedBundle:Pago:confirm_delete" }
